apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "anzounstructured.cambridgesemantics.com/v1beta1",
          "kind": "AnzoUnstructured",
          "metadata": {
            "name": "au01",
          },
          "spec": {
            "anzoMicroservicesLeader": {
              "resources": {
                "limits": {
                  "cpu": "2000m",
                  "memory": "4Gi"
                },
                "requests": {
                  "cpu": "2000m",
                  "memory": "4Gi"
                }
              },
              "size": 1,
            },
            "anzoUnstructuredWorker": {
              "resources": {
                "limits": {
                  "cpu": "2000m",
                  "memory": "4Gi"
                },
                "requests": {
                  "cpu": "2000m",
                  "memory": "4Gi"
                }
              },
              "size": 1
            },
            "serviceAccountName": "unstructured-operator",
          }
        }
      ]
    capabilities: Basic Install
    categories: Database, Big Data
    description: Kubernetes Operator for Anzo Unstructured
    containerImage: registry.connect.redhat.com/cambridgesemantics/unstructured-operator:1.1.0
    createdAt: 2020-10-21
    certified: "true"
    support: Cambridge Semantics
    repository: ""
  name: unstructured-operator.v1.1.0
  namespace: default
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AnzoUnstructured is the Schema for the anzounstructureds API
      kind: AnzoUnstructured
      name: anzounstructureds.anzounstructured.cambridgesemantics.com
      version: v1beta1
      resources:
      - kind: Service
        name: ''
        version: v1
      - kind: StatefulSet
        name: ''
        version: v1
      - kind: Pod
        name: ''
        version: v1
      - kind: ConfigMap
        name: ''
        version: v1
      - kind: Secret
        name: ''
        version: v1
      - kind: AnzoUnstructured
        name: ''
        version: v1beta1
      - kind: PersistentVolumeClaim
        name: ''
        version: v1
      - kind: Event
        name: ''
        version: v1
      - kind: Deployment
        name: ''
        version: v1
      - kind: ServiceMonitors
        name: ''
        version: v1
      - kind: ReplicaSet
        name: ''
        version: v1
      specDescriptors:
      - description: Resource Specification for Anzo Unstructured Leader
        displayName: Leader Spec
        path: anzoMicroservicesLeader
      - description: Resource Specification for Anzo Unstructured Worker
        displayName: Worker Spec
        path: anzoUnstructuredWorker
      - description: Service account used to deploy Anzo Unstructured
        displayName: Service Account
        path: serviceAccountName
      statusDescriptors:
      - description: Current phase of Anzo unstructured CR like Creating/Running/Failed
        displayName: Phase
        path: phase
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:phase'
      - description: FQDN of Microservices Leader
        displayName: LeaderFQDN
        path: leaderFQDN
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:text'
  description: "The Unstructured Operator provides the way to install and configure an anzo unstructured setup on Red Hat K8S environment.\nCurrently, this is possible only through existing Anzo installation.\n\n### Installation\n Refer [installation instructions]( https://github.com/cambridgesemantics/csi-k8s-operator-anzo-unstructured/blob/v1.1.0/README.md )\n\n### Documentation\n\nYou can find our documentation [here.]( https://docs.cambridgesemantics.com/anzo/userdoc/cloud-deployments.htm )\n\n### Support\n\nWe offer Support to our customers through [ Cambridge Semantics Customer Center ]( https://customercenter.cambridgesemantics.com/ )."
  displayName: Anzo Unstructured Operator
  icon:
  - base64data: "iVBORw0KGgoAAAANSUhEUgAAAJYAAACWCAIAAACzY+a1AAAEwGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS41LjAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIKICAgIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIKICAgIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIKICAgIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIgogICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIKICAgZXhpZjpQaXhlbFhEaW1lbnNpb249IjE1MCIKICAgZXhpZjpQaXhlbFlEaW1lbnNpb249IjE1MCIKICAgZXhpZjpDb2xvclNwYWNlPSIxIgogICB0aWZmOkltYWdlV2lkdGg9IjE1MCIKICAgdGlmZjpJbWFnZUxlbmd0aD0iMTUwIgogICB0aWZmOlJlc29sdXRpb25Vbml0PSIyIgogICB0aWZmOlhSZXNvbHV0aW9uPSIzMDAuMCIKICAgdGlmZjpZUmVzb2x1dGlvbj0iMzAwLjAiCiAgIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiCiAgIHBob3Rvc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIKICAgeG1wOk1vZGlmeURhdGU9IjIwMjAtMTAtMjBUMTU6MDU6MTAtMDQ6MDAiCiAgIHhtcDpNZXRhZGF0YURhdGU9IjIwMjAtMTAtMjBUMTU6MDU6MTAtMDQ6MDAiPgogICA8eG1wTU06SGlzdG9yeT4KICAgIDxyZGY6U2VxPgogICAgIDxyZGY6bGkKICAgICAgc3RFdnQ6YWN0aW9uPSJwcm9kdWNlZCIKICAgICAgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWZmaW5pdHkgRGVzaWduZXIgKEp1bCAyOSAyMDIwKSIKICAgICAgc3RFdnQ6d2hlbj0iMjAyMC0xMC0yMFQxNTowNToxMC0wNDowMCIvPgogICAgPC9yZGY6U2VxPgogICA8L3htcE1NOkhpc3Rvcnk+CiAgPC9yZGY6RGVzY3JpcHRpb24+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+oBUXeQAAAYNpQ0NQc1JHQiBJRUM2MTk2Ni0yLjEAACiRdZHPK8NhHMdfGyImkx0cHNbCadNQ4qJsCbWkmTJctu/23dQ2377fLS1X5aoocfHrwF/AVTkrRaTk5OBMXNDX57utJtnn6fN8Xs/7eT6fnufzgD2SUbJGvR+yubwengi456ML7sZnmnHRjgdnTDG0sZmZEDXt4w6bFW98Vq3a5/61lkTSUMDWJDyqaHpeeFI4tJrXLN4WdinpWEL4VNirywWFby09XuYXi1Nl/rJYj4SDYHcKu1O/OP6LlbSeFZaX053NFJTKfayXOJK5uVmJHvEuDMJMEMDNFOMEGaKfEZmH8DFAn6yoke8v5U+zIrmKzBpFdJZJkSaPV9SCVE9KVEVPyshQtPr/t6+GOjhQru4IQMOTab71QOMWfG+a5uehaX4fQd0jXOSq+SsHMPwu+mZV696HtnU4u6xq8R0434DOBy2mx0pSnbhdVeH1BFqj0HENzYvlnlX2Ob6HyJp81RXs7kGvnG9b+gFJEWfY7/NllgAAAAlwSFlzAAAuIwAALiMBeKU/dgAAFnBJREFUeJztnXl4G8Xdx2dXt2RZliz5lu/4vq/ETpzECSSEhAQIUPIGaLnC0wYo70shBCgF3hIgfZuWpiE07QuU420JpZAQchBykBAn8Rknvq/4kG3Z1i1bt7TvH4vXo8PyyoWXd59nPo/+2JndnRntd+c3M7/5ycayT7wFEEwG/6EbgPhXQRIyHiQh42HDiXJpbIUs7odqCoImdbrRev0YlfSSsEIWtz2t7P+8SYhQaYAlRIaU8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8bDnvwQxg9ZhPTM52GXWTtinTU67lCuI4gkLJFHV8kQxmxtSUQQAx9V9tVqVymoatpoJglgSGV8VmVApS5Bx+SEV9S9J2GIcPzjcQSVzwuVbE/No3jvtcr7WVYtjGAYwHAM4wDAMeyC5MJYfFvzGc5qh4+o+KvkjZU6hJJo8Pqru/UYzHOKX8OLB5KK0MKl/vspqfrnj/AXNMBHoLjaGr4tJ25lVFcGh9fSvGMZf66q9apyAMz8d6fp0pIuPs1/OXb4hdhH9Nv9LEu7pvgz/kejDYz0rFUnxAjGde+0e9ycjnT6ZDfqxDys2CVmcIDf2TOk+G+2mksvkSkrCVuMkfGoBbIzLSANeEhIAfKxq3911yeJ2znWXi/B8PtZTq1W9nLu8RpEcvIoPh1pf6bww11mbx/X0tdMtxomnMyo5OK1hbuFjYaN+DNYPAOAmPPv7mxZcIACgy6zdce20hwj4rv8AqG3T2xq/eLH9fBD9KLQO6/bmEztbz5hdjrmuaTKoX+u6COdE80Wl0thUUQSc+eFQ68sd52k2cuESvhVIrUOjXUMWI53bMSxw/qmJgb19DQtu1XeI0+P5afOxC1qV/6lonqhUGhvQbB4a7d7ZeibgO6ixW/695aSb8JDJPIniw4pbzyy/5/3yjUeW/uj08ns2xKZTF/9zpLPDrKHTzgUa0mvGiYDfzU0Qb/Y3vZZXs7BiSf7U35QmksLfhyZxAnGhJBrHAAYwAACGYTgAGEa+LRiZjwGAAQzDwIDFOGwx+ZQggmz4W/2NXWYtfDZFFPFEekVRRLSCJwQAEACMWc11+rE9PZc1dgt12emJgc9HuzfGZfgUflDVMTlzWXFE9LtlG2FTGcMXvZ6/OkUk3dtbTxb+etfFd8pumeNVn2WBEgbsgiRHxnq2pRT7WAZ/grfs+bazicLwAknUvC3BoJLuScy7h9586qJ25NErx33a81LuivyZGltNkweuN8Nnf5Jc8Fh6OR9nw5lxAvGtAnGNIumVzm+OjPVSp17pvLA4Mj6aJ4KrqJ156YUszp7CG/2HOgyAbSnFX473k69OnW5UZTEpheHBv8tCDGmnWXtmcpBKxvLD7lbmUEkPQezvawy1zPQw6aIwGZV0eNyPXjmhtk0toHnzcmK8/5Gmo1a3i8phYfh/FdxwR3wWVfvO1jNuaEh+OrPyqYxKWD8YCYe3O3/1FmUulWN2OV5o+xo2p9MuZ8vMFHSxzFddqCXYfUn5VHLY6msn/FmIhD5d8OGU4kdSS+B36qi6t2dKF7wQzLsfClmcPxavlXB4VI7GbtnefAJ+0N8JHw23/0fLSdfMgAQA4OGsPxatXReTRuWc1wz3TempZKk09t7EfDAfT2YsVgpme8x5zXA/VEjvtI4aBUuk0UHKSRbOGjDV9yFh75T+y/F+KhnFE94WnxnNE90+8woDAAgA9s3XEf0NqVIQ/vvCNSxontNh1uxsPfNdTVAJAN7qb3qp4zxcnJDFOVC6foUiEb7y9MQAdYxj2K7clfhcsy/vol7MWQ7nnJqcLScK6nZTrmDzWw42K4rOYZu33pAlPHDdqws+mFLEw1kAgIeTi1hQ3V+O93d6zwXosFgWtzNrKZzz5Xj/m/0hm2V/PATxaueFP/TWw5kSDu/dslvKpbE+F9fpR6njVFHEvKMRRYUsFja29brZcqJ4IvbM8+kNaqIu6Uao46KIYP2VJDQJBy3Go5BnRMYV3BmfTR7HCcSbvOdgfwy6NsDmeK+3KHPvTMiGc97sazwGVepbzryNBsBFeJ5pPfPBUCucqeAJ3yvfmCdR+FxMADBum6aSeeG+FwSBheHZ4ZFUctw+DZ3CqFeB9NIFLMHmdh0a+9Y7wcNZxREx81YamoQH+pths/ZAciGfNfvSbUspgg3O6YmBNtNkSOUDADAAns9aVuLd9Gdbz7QaQy6KxOZ2Pdp84shYD5wZLxB/UL4JnkBRGJ02eKTMEstDqi4bun4SWmkAAH48M0/xEMTzbV9rvM8CAAgAXu44Tw3DpdJY0sIFJwQJR6zmw2Oz7qsIDh+eiAIAEoWS9TFei7m9vQtZpHNw/A9Fa2IgZ6nd495+5Tj8UtPE6LQ/2HjknGYIzkwVST+o2DSXeRR4u/d0DmtINWqh6yO5AvjU5vgs6qVpM01uvvTJMXUf6cpxE8QVw/g9dZ9RDkIMgJ+lldKpMYR14Z+vX4Hn2QanbfHpd32uIYDX1OOcZqjFOE75MOkj4wr2Fa/devmQzfPtjHTSbnms+cR75RvpFzJhn3648ajP3DgnXH6gZH2Q3QAezgrn8ExOO5lsN9FykVDA1/t4zFkY/mxW1UONX5CPcdJuefLqVziGxfDDJmzTcNcHAPwkuaCEhhUF9Huh2jb96aivV9pNeHw+/rPHuTrivGNYtli+K28lnNNqmnyu7SzN+emgxbi17pCPfiURMe+U3TLvbk4KNK1vNU3SnxAbnXZ4JZcq8t30WCyLf7vsFhnUOz0EMWo1++h3b2L+k4uW0KyUroRvD1xxejzzX+dHrVbV6O0NDwgWSNObYtIeSS2Bc46p+z5StXvdGGha1GHWbK07NGI1w5nL5Mq/lK6ns7FXE5VEHRuctoPD7UEuhvmT94o5PdC+Vbk09p+VmwP2MAyAZXLlvuK1z2RV0VnGkNCSUOuwfqzqmP+6OQg4NQ2omT+PpZX5bN/4CONPnW70vvrDPmPYmujUfUU3wZOvINwYlQI/wd3dF1XzVQoAaDKo/zp41StHr54OtASM4ol8HIFynvDhlKLj1VsOlNxco0imqx4AgOZY+M5Ai93jppIVsrjgLlCnxwPvBV7WjV7WjS5e0D96xjHs9fyaLXWfwe6SIJyaGHjy6lcOqLUAgNviM1/OWQ4vW4OTIor4SVLB2wMtZNLqdj119dTeojVynnCuW65PG3Ze892g+Ntw21cT15/KWLI+dpGPKu3euxD3JxXen1xAs3k+zC+hwWn723AbleTj7D0FN8i851r+6By2M5BvYm9vfUXFJvhr0LYTIIzNfbPopjsv/5OaYszF6YmBn7d86TMeJwklJRExh0d75roLZmVUkpTDBwA8ll5+dnKof/rb96bFOH5L7cFfZi9bF5Pu03A3QXwwdO33PXV27/eGZNJuefra6Y9UHc9nLc0Uzy4ZfWZJOdBqkuT6tOGyblTIYlcrEqVBgwHml/C9wWuwo/KOhKx59QMAbE8rhSVsMqhrtaqlkQnz3hgQpTD8dwU3bmv6wu03mYEfaIdZ4z+fGrQYf9n2Nc2KPhbfTj4vHs56La9mS92nVI1Gp/0XV0+9O3i1SBKdG65QCsP7pvRtpskGvZpSei4a9WObL32yRZn7eHq5mM2dtFt8JMz2Xn0eVLV/NT5we3zmpMPyWPOJHZmV+XNv2swjodnlgJ0abAx/ILko+C0kOeHyGkWyT0esikygnjjNsZCiMjJ+R2bVrrlDFgAA9E0lHfIkip+nV+zpuQxnthongzsZWBi2RZl7TN2n9R6MPQTx4VDrMXXvcnniUXUfbOr5LDacHLNNHR7t+fmiin19DUIW5/X8VU+0nPx4ye1z1TjPd/5wqHUKCiO4NS4jhh94l8Sf7d4r06vGifPeS+xQ2ZqYBzvT/fluJQQAPJRS9E7Zhjh60UAAACGLs7943bNZS48uu/vHSQUsv9FC57B9NtrtM1Tb3K776g+rZ7x6zQb1prgMh8ft8LjNLkckT5AklATxdwf7zha3E55i4Rj2UAqtLkhCdkQ4Z29vA2XmQuuDM7e8kL2seG7PL5v+AEubxbL4zyrv8HHbBuTmmPTDVXcukysBAGI2d0dm5aeVd841iWNhOLy8GbAYX+uqJY9lXEHftB4AUCiJDmfzBqeNQxZjGHvOkDAs+8RbVGJ7Wun2tDIq6SI8JudsF8QxQDPIjsLmcVlcXht+ERweOV/3EATsMONgeJD5HozV7TI4Z19JKYdPLRWmXI4goUd0kHOFc8WNNejHPh/rOTUx4LNciReI10SnrI9ZlBMewJtKxovu7roIf1kJh7e/eF1RRLTN7Xqg8cgVwzgAAAPg6LK7k4QSh8f9UOMXj6WXKwViDs76ZKRTbZt6Ibuaun1fXwO8lxdsLGRjeKhhqT7wcTafG7gKHMPmDRkNiIDFFrAC3xjG5oaFGJJLnzJpbJk09lfZ1VqHdcI+bXI6ZFx+NF8k4fCD9H0MgHUxaSsUiW/01L8/dI3M3JFZRe4i8VnsN4tvWn72fRfhIQBoN2mShBIuztqdv/qVzm+mXE6L21kmjd2RWRWkYSiaOzRwDFPwhAp6BoNCyOI8ml72wdA1chyBO4aYzaO8a1T/juGL9hat9RAENteeHMRCJLxqnLB73PBO6UXtiITDywmXOz2eM5MDMfwwKnLJ5nGdmxzKDVeQIcIuwnN6YmDAYgxn86rlyhi+6Jxf/DUbw6vlymvGCY3DCgAIY3NLIqKpqcqgxdg7pa9RJFEOlHaTxui0V0bGUyXYPK52k6bTrLW5XbH8sGq5ssOsnfKzsRXSOLVtSmU1w7v2LcZxp8dTJo0FADTqx0wuBwAggsMvlERRNQ5bTb2QqyGczS2VxgIALulGyAWYgivMEMu40FaRmM3NFEeS2+BfTw5VyxPJspoNauqaFG+HCU0f20Ik3N/fOGGzfFK5mcp5sf1cYUTU7vzVZpf9iZaTQhbn2LK7yVdVa7c+0XLypZzldyZkT7uc99Uf7jBrlMJwjd1idjm2KHO2Nx/3KZ/PYjetfvAPvfVUnKOMK9iWUkzGBR1X973RW3/lhoe42LcP6K+DV5sM6pPV/0Ymmwzqna1nhi0mDo57CMJNEH8uXf9qZ63/6u3TyjsOjXb/XdXetPpBKvPNvkadw0ZO4l/tqqUWcNE80ePp5bfFZwIAjo71vgEFAOSEy/+xZDMA4Kmrp6i1BBvDb4vPfCazSjAzVJdL40gJ/zbcxsbwgogos9Px+swshs9il/rFD9DhezGkFrdzT8/lV/2iSf+uauswa94tu6VCFucmPE6Ph8din11xDwDggkb1XNvZAyU3Z4hl+Mx0dVGY7M+lN+sctt92X3q9q7ZGkTRvDMSwxfRAw5FkoeR/Km7NkygIAqisJjlP+F75Rhfh1jtst138x+Pp5bfHZwK//byAlEtjf1OwesJm2dV14Vft51ZFJZMxWhgAJ2ZeGnhjdnVU8s7MqlHb1NnJwXcHr16fNvy1fCP5fW6Lz/xI1U6uKN4fuga8V1g7MirpbPD68738OC1OID402u3zsw8AgNo2zcbwLHEkAICF4XwWGwMgiieK4onI5yLl8qN4ImpqysHxKJ4oSxx5b1I+AUDffE4QAMBvui9xcdbbZRuKIqLZGM7B8RRRhJjNlXH5UTwRaRjEbC5ZKZ11JA9nR/FEeRLFXQk5LsIzOBOrjmFYgkBMfuChUcDixAnEZdLYX2QseS5raYN+7OxMwGaWOHJX3sqAOt2VkHOX9/45fb4XCe9KyE4USn7d+Y2Pu2tTbAYBiEeajoW0/07MBNGmB4qT8LmyTj96c0waHRdgSBAAXNSqcAyjhiuCIK5PG8jPXDv7d8RnszCsxTBO5dwck/6PJZs3xC4iDQAfZxdKov+7dMOLOdULXtJ+L4aUi7N2ZFZubz5+aKy7Qjq7ts2TKA6UrH/q2qmNFw4+m7V0k1/Iug+DFuO2pqN9U/ox29SqqOSE+bwkeofN5LQnCecJJA+JVtPktsajXVPaSbvljvgsaj1OALD+wkfk8aa4DP9RAwDAwXE5Vzhq89qoSguT7s5fRQBgcNoigi5IaPJ9LSpWKpKWRibs6b78l9L1cH5lZPwXS3/0q/ZzO1vP6BzW+5MLgxSCA0zAYuMYFsHh/7bghnkrFbO5LAzXO0OLdgkOjmECNhsAoBSEw2GiGAD7S9aRx3MtcG0el8ZhiQl0FgMg+P5DCC1cwD0cjGVy2SkT6SYIs8vB8TbxGAA7s6oMTrv/ry8kHN6eghuWyxP39jb47zzAKIXhbxSu+XXuCoPTRsUfkxXBG08ml50cYDg4niKSfKMZph89zMFxp8djg7ZiTE4HF3LQ5IjlbxSueSazathqqtXN/hIIw7Dl8kTyEzASDgBwdmLQTRDZIcbAhcpCJMwUR45YzVdmTPxFncrgtOX4NTRVJN2amHsCCv2erRXDEgRiGU9Ax4wslsUvlsXv7a0nIz/IXbfPZ36DonfaarUq6jHdn1TYadbu72+iqWGmONJNeKg41WGrqcU47v/Q10anZoojf99TR/PlIAA4pxn6ZfvXmeLIVVHJ9NqyQBZiSLcocz5Wtf+4/vCa6FQn4T49MZgolAQc2LanlR0Z66G87AdV7Z1mbaJQorKYPlK1/yytjObq9fH08q11n30y0nm3MmeJLH6xLO433RfPaQaThJKj6j4WwKkQm01xGd9oh/f1NVzQDi+RxQtZHJXVtEWZC2+3wtwQlZIbrniu7eyx8T4FT3hM3Sdmc/3NO45hj6eXbW8+8dXE9TXRqQAAD0E80XKSPCtgsamxsEE/9kjTUfKXb9F80e8Kb1zYUoE+LMW9G6hEhSyugkZ4hIDFWRWVLGRzLutGBy3G5XLlrtyV5MTaRRDNhvGlkQlk5A8PZ0Xzw3QOW7U8MVkkuT5tODTa/eX49WGraXNC1k9TS9gzJkvvtA1aTGtj0ihPeteULoLDr1EkAQBi+WF6h+36tGFNdCqOYTWKZAVP2DOlq9OPZYfL/zN3BRWUjWHYmujUFFGEymK+qFNdMagdhGdVVDI5A/y2efIEKraMheGrFEkynqDdpLliGC+WxOzKr6HCltpMmjhBWFVkAgAgWRQxbDFN2KdXKJLUtimNw2JxO8mP0+Mhf03YYhwn7XyWWH5fUv4L2dWhuuLoUK8fhX9fHWynAvH/E5+dCvR3ZxgPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZD5KQ8SAJGQ+SkPEgCRkPkpDxIAkZj9dfyK/TjQLQ8EM1BUGTOt0onPSSsF4/Bv/pdQQjQIaU8SAJGQ+SkPH8L2oIn4qRBBjMAAAAAElFTkSuQmCC"
    mediatype: "image/png"
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          verbs:
          - get
          - list
          - watch
          - create
          - delete
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - extensions
          resourceNames:
          - nfs-provisioner
          resources:
          - podsecuritypolicies
          verbs:
          - use
        - apiGroups:
          - anzounstructured.cambridgesemantics.com
          resources:
          - 'anzounstructureds'
          - 'anzounstructureds/finalizers'
          verbs:
          - '*'
        serviceAccountName: unstructured-operator
      deployments:
      - name: unstructured-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: unstructured-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: unstructured-operator
            spec:
              containers:
              - command:
                - csi-k8s-operator-anzo-unstructured
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: unstructured-operator
                - name: RELATED_IMAGE_ANZO_MICROSERVICES_LEADER
                  value: registry.connect.redhat.com/cambridgesemantics/anzo-microservices-leader:5.1.2
                - name: RELATED_IMAGE_ANZO_UNSTRUCTURED_WORKER
                  value: registry.connect.redhat.com/cambridgesemantics/anzo-unstructured-worker:5.1.2
                image: registry.connect.redhat.com/cambridgesemantics/unstructured-operator:1.1.0
                imagePullPolicy: Always
                name: unstructured-operator
                resources: {}
              serviceAccountName: unstructured-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - namespaces
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - unstructured-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - anzounstructured.cambridgesemantics.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - policy
          resourceNames:
          - privileged
          resources:
          - podsecuritypolicies
          verbs:
          - use
        - apiGroups:
          - ""
          resources:
          - pods/exec
          verbs:
          - create
        serviceAccountName: unstructured-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - Big Data
  - Database
  links:
  - name: Unstructured Operator
    url: https://github.com/cambridgesemantics/csi-k8s-operator-anzo-unstructured/blob/v1.1.0/README.md
  maintainers:
  - email: frank@cambridgesemantics.com
    name: Frank Schwichtenberg
  maturity: stable
  provider:
    name: Cambridge Semantics
  version: 1.1.0
