apiVersion: anzounstructured.cambridgesemantics.com/v1beta1
kind: AnzoUnstructured
metadata:
  name: au01
  labels:
    testkey1: testval1
    testkey2: testval3
spec:
  serviceAccountName: "unstructured-operator"
  #bootProperties:
  #  testKeyCommon: testValCommon
  anzoMicroservicesLeader:
    size: 1
    affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: cambridgesemantics.com/node-purpose
             operator: In
             values:
             - anzograph
    tolerations:
    - key: "cambridgesemantics.com/dedicated"
      operator: "Equal"
      effect: "NoSchedule"
      value: "anzograph"
    image:
      registry: "us.gcr.io/cloud-sandbox-1162"
      name: "cambridgesemantics/anzo-microservices-leader"
      tag: "latest"
      pullPolicy: "IfNotPresent"
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "16000m"
        memory: "48000Mi"
    #bootProperties:
    #  require-mutual-authentication: "off"

  anzoUnstructuredWorker:
    size: 2
    affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: cambridgesemantics.com/node-purpose
             operator: In
             values:
             - anzograph
    tolerations:
    - key: "cambridgesemantics.com/dedicated"
      operator: "Equal"
      effect: "NoSchedule"
      value: "anzograph"
    image:
      registry: "us.gcr.io/cloud-sandbox-1162"
      name: "cambridgesemantics/anzo-unstructured-worker"
      tag: "latest"
      pullPolicy: "IfNotPresent"
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "16000m"
        memory: "48000Mi"
    #bootProperties:
    #  require-mutual-authentication: "off"

  volumes:
  - name: nfs1
    mountPath: "/opt/nfs1"
    pv:
      capacity:
        storage: 5Gi
      accessModes:
      - ReadWriteOnce
      storageClassName: ""
      persistentVolumeReclaimPolicy: Retain
      nfs:
        path: "/var/nfsshare"
        server: 10.104.20.4
        readOnly: false
    pvc:
      accessModes:
      - ReadWriteOnce
      storageClassName: ""
      resources:
        requests:
          storage: 2Gi
  - name: nfs2
    mountPath: "/opt/nfs2"
    pv:
      capacity:
        storage: 5Gi
      accessModes:
      - ReadWriteOnce
      storageClassName: ""
      persistentVolumeReclaimPolicy: Retain
      nfs:
        path: "/var/nfsshare"
        server: 10.104.20.4
        readOnly: false
    pvc:
      accessModes:
      - ReadWriteOnce
      storageClassName: ""
      resources:
        requests:
          storage: 2Gi
