###########################################################
# Copyright (c) 2016-2019 Cambridge Semantics Incorporated.
# All rights reserved.
###########################################################

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: unstructured-operator
subjects:
  - kind: ServiceAccount
    name: unstructured-operator
    namespace: default
roleRef:
    kind: ClusterRole
    name: unstructured-operator
    apiGroup: rbac.authorization.k8s.io
