apiVersion: anzounstructured.clusters.cambridgesemantics.com/v1
kind: AnzoUnstructured
metadata:
  name: au01
spec:
  auWorker:
    nodeConfig:
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: anzounstructured
        serviceName: au-au01-w
        template:
          metadata:
            labels:
              app: anzounstructured
          spec:
            containers:
            - image: registry.connect.redhat.com/cambridgesemantics/anzo-unstructured-worker@sha256:70dd265022423db9b7026fddfd98524e36e58e87d228a5579d3898f57ad906f4
              name: w
              resources:
                limits:
                  cpu: "2"
                  memory: 4Gi
                requests:
                  cpu: "2"
                  memory: 4Gi
            serviceAccountName: unstructured-operator
  msLeader:
    nodeConfig:
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: anzounstructured
        serviceName: au-au01-ms
        template:
          metadata:
            labels:
              app: anzounstructured
          spec:
            containers:
            - image: registry.connect.redhat.com/cambridgesemantics/anzo-microservices-leader@sha256:2069afa1555213cc33905d9fd473b52ec7c68e354c669c8c4f7ac8fd3ba3e23b
              name: ms
              resources:
                limits:
                  cpu: "2"
                  memory: 4Gi
                requests:
                  cpu: "2"
                  memory: 4Gi
            serviceAccountName: unstructured-operator
status: {}
