apiVersion: anzounstructured.clusters.cambridgesemantics.com/v1
kind: AnzoUnstructured
metadata:
  name: au01
spec:
  auWorker:
    nodeConfig:
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: anzounstructured
        serviceName: au-au01-w
        template:
          metadata:
            labels:
              app: anzounstructured
          spec:
            containers:
            - image: registry.connect.redhat.com/cambridgesemantics/anzo-unstructured-worker@sha256:a00c57baade38e08ac009880dc57cb6165bbf89d1906d4c92e858a1db09ef73c
              name: w
              resources:
                limits:
                  cpu: "2"
                  memory: 4Gi
                requests:
                  cpu: "2"
                  memory: 4Gi
            serviceAccountName: unstructured-operator
  msLeader:
    nodeConfig:
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: anzounstructured
        serviceName: au-au01-ms
        template:
          metadata:
            labels:
              app: anzounstructured
          spec:
            containers:
            - image: registry.connect.redhat.com/cambridgesemantics/anzo-microservices-leader@sha256:ba66cb6b55a2313a40a4f42dd6c046032e32ce670de3d59f1298bc6ad57519c2
              name: ms
              resources:
                limits:
                  cpu: "2"
                  memory: 4Gi
                requests:
                  cpu: "2"
                  memory: 4Gi
            serviceAccountName: unstructured-operator
status: {}
